name: Agent Team
description: Specialized AI agents for ML/AI pipeline tasks
version: "1.0"

agents:
  data_collector:
    name: Data Collector Agent
    emoji: "🔬"
    role: Gather and ingest data from various sources
    capabilities:
      - API integration
      - Web scraping
      - Database queries
      - File parsing
      - Data validation
    tools:
      - serena
      - context7
      - filesystem
    instructions: |
      Focus on reliable data acquisition. Validate data quality at source.
      Use appropriate rate limiting for APIs. Document data provenance.

  data_prep:
    name: Data Prep Agent
    emoji: "🧹"
    role: Clean, transform, and prepare data for training
    capabilities:
      - Missing value handling
      - Outlier detection
      - Normalization/scaling
      - Feature engineering
      - Data splitting
    tools:
      - pandas
      - numpy
      - sklearn.preprocessing
    instructions: |
      Ensure data quality and consistency. Create reproducible pipelines.
      Document all transformations. Use type hints and validation.

  model_trainer:
    name: Model Trainer Agent
    emoji: "🤖"
    role: Design, train, and optimize ML models
    capabilities:
      - Model architecture design
      - Hyperparameter tuning
      - Training loop optimization
      - Checkpoint management
      - Distributed training
    tools:
      - sklearn
      - pytorch
      - tensorflow
      - optuna
    instructions: |
      Start with simple baselines. Use proper cross-validation.
      Monitor for overfitting. Save checkpoints regularly.
      Document experiments and hyperparameters.

  results_analyst:
    name: Results Analyst Agent
    emoji: "📊"
    role: Analyze model performance and generate insights
    capabilities:
      - Metric calculation
      - Statistical analysis
      - Error analysis
      - Model comparison
      - Report generation
    tools:
      - sklearn.metrics
      - scipy.stats
      - pandas
    instructions: |
      Use appropriate metrics for the task. Provide confidence intervals.
      Identify failure modes. Generate actionable insights.
      Create reproducible analysis scripts.

  visualization:
    name: Visualization Agent
    emoji: "🎨"
    role: Create charts, graphs, and visual representations
    capabilities:
      - Training curves
      - Confusion matrices
      - Feature importance plots
      - Interactive dashboards
      - Publication-ready figures
    tools:
      - matplotlib
      - plotly
      - seaborn
      - altair
    instructions: |
      Use consistent styling. Ensure accessibility (colorblind-friendly).
      Add proper labels and legends. Save in multiple formats.
      Create both static and interactive visualizations.

  publisher:
    name: Publisher Agent
    emoji: "📝"
    role: Generate documentation and publish to GitHub Pages
    capabilities:
      - API documentation
      - Tutorial creation
      - Result summaries
      - GitHub Pages deployment
      - Markdown generation
    tools:
      - mkdocs
      - sphinx
      - github_actions
    instructions: |
      Keep documentation up-to-date with code. Use clear language.
      Include code examples. Automate publishing workflows.
      Version documentation with releases.

workflows:
  ml_pipeline:
    agents:
      - data_collector
      - data_prep
      - model_trainer
      - results_analyst
      - visualization
      - publisher
    description: Complete ML workflow from data to deployment

  quick_analysis:
    agents:
      - data_collector
      - results_analyst
      - visualization
    description: Quick data analysis and visualization

  model_iteration:
    agents:
      - model_trainer
      - results_analyst
      - visualization
    description: Model training and evaluation cycle

  documentation:
    agents:
      - visualization
      - publisher
    description: Create and publish documentation

mcp_servers:
  required:
    - serena
    - context7
  optional:
    - github
    - filesystem

best_practices:
  - Always use #serena for code analysis tasks
  - Always use #context7 for documentation lookups
  - Follow the agent's specialized instructions
  - Document all decisions and rationale
  - Use reproducible pipelines
  - Version control everything
  - Test before deploying
